<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title><?php echo $this->headTitle(); ?></title>
    </head>
    <body>
        <div id="menu">
            <?php echo $this->menuAuth(); ?>
        </div><!-- div#menu -->
        <div id="content">
            <?php echo $this->content; ?>
        </div><!-- div#content -->
    </body>
</html>
